#!/bin/bash

#systemd service to cleanup old kernel

if [ -e /usr/lib/modules/.old ]; then

	oldkern=$(cat /usr/lib/modules/.old)
	currentkern=$(uname -r)
	
	#check if old is no current and in this case remove the modules
	if [ $oldkern != $currentkern ]; then
		rm -r /usr/lib/modules/$oldkern
	fi
	#remove only the hidden file
	rm /usr/lib/modules/.old
fi

#backup old kernel

#rsync -AHXal "$${i}" /usr/lib/modules/.old/
#rm -rf "$${i}"
#done

